### ISSUE TITLE
Running dynamically provisioned agents with WSL

### ISSUE THREAD

**Issue by jasonsalas** [PacktPublishing/Continuous-Delivery-With-Docker-and-Jenkins-3rd-Edition#1]
First, *fantastic* book! It's a great read and really good run-through of the topics. In getting the demos to run on my end, using a Windows 10 laptop with Windows Subsystem for Linux 1.0.3.0, I'm able to get Jenkins up and running for the master node haven't been able to execute the build jobs with a dynamically-provisioned agent. The master works just fine, but the agent's not communicating.

I've noticed a couple of things in my environment that differ from the book:
- i don't have a _docker0_ network interface 
- the file _/lib/systemd/system/docker.service_ doesn't exist on my Jenkins container
- for the **Docker Host URI** setting when configuring my agent details, Docker Desktop's Settings menu I can enable _"Expose daemon on **tcp://localhost:2375 without TLS**"_, but the book (and my container) cite **tcp://172.17.0.1:2375**

The agent gets setup just fine, but it just won't talk to the master, apparently. Does anyone have any ideas?  Thanks!

**Comment by leszko** [comment]
Thanks for the comment @jasonsalas !

Docker is running "natively" only on Unix systems. In Windows (and macos) it's virtualized. So, technically your Docker engine is running in a kind-of VM that Windows is connected to. That is why some of the things may not work the same way.

**Comment by jasonsalas** [comment]
Gotcha. Thanks, @leszko! I'm really enjoying the book...and I'm actually trying to see if I could help by "porting" the code examples to run in WSL, too. I'll let you know. 😄

**Comment by jasonsalas** [comment]
Gotcha. Thanks, @leszko! I'm really enjoying the book...and I'm actually trying to see if I could help by "porting" the code examples to run in WSL, too. I'll let you know. 😄
